### ISSUE TITLE
Error -101 after wake up from hibernation

### ISSUE THREAD

**Issue by mac-can** [mac-can/RusokuCAN#11]
If the Mac goes into hibernation mode and then wakes up again while a client application has loaded the library (by a call to can_init or InitializeChannel), any further call to a library function returns the error code -101 (vendor-specific error, hardware error ). This error can neither be cleared by re-initializing the CAN channel nor by restarting the client application; error -101 remains.

It seems that the hardware is stuck in a state where it does not accept the control commands or is incorrectly controlled by the library functions in this state.

Workaround:
- Unplug the TouCAN adapter, plug it in again and restart your client application.

Action points:
- Further investigation and clarification with hardware manufacturer required.

Additional information:
- CAN Library: MacCAN-RusokuCAN Version 0.2 (Commit 52f784a of February 28, 2021)
- CAN Hardware: TouCAN USB (Model F4FS1, Hardware 1.0.0, Firmware 1.0.4)
- Mac Hardware: MacBook Pro (2019, x86_64 architecture) running macOS 11.3.1

**Comment by rusoku** [comment]
I can confirm that after Mac hibernation mode adapter is stuck in a wrong state.
After Windows 10 OS hibernating mode adapter works without any issues.

**Comment by rusoku** [comment]
After hibernation USB host send several req frames and goes to error mode (101).
I don't see any stall packets ... Need to go deeper to adapter code...

![image](https://user-images.githubusercontent.com/46974254/117696907-8488cc80-b1ca-11eb-9b2a-d6bbaf4ff658.png)

**Comment by mac-can** [comment]
As mentioned by [rusoku](https://github.com/mac-can/RusokuCAN/issues/11#issuecomment-836997912) in suspend mode the CAN interface will be closed (I guess this is _`de-intitialize`_). When the Mac awakes from hibernation no control command to the interface will succeed. Function `TeardownChannel` checks the state of the interface, and stops and de-intitializes the CAN interface when required by its current state. After this the error status is queried, and if there is an error pending (there is always an error set in suspend mode) the function commands a clear error request. This clear error request fails because the interface must be initialized to accept this control command. The same control sequence is also executed at the beginning of function `InitializeChannel`, therefore we don´t get out of this vicious cycle.

The solution is, when there is an error pending, first to initialize the interface, then to clear the error and to de-initialize it again. Afterward the function `TeardownChannel` as well as `InitializeChannel` can execute their normal control command sequences. 

Fixed by commit 3feff400fc28956b46e4ac0037cabfd4f5a5181a.
